### ISSUE TITLE
Magnet Module Lag and Config Disable

### ISSUE THREAD

**Issue by wiilover22** [Eximius88/ModularPowersuitsAddons#1]
I'm using:
Minecraft 1.6.4
ModularPowersuits-1.6.4-0.10.0-96
Numina-1.6.2-0.1.2-56
powersuitaddons-1.6.4-884
mcpc-plus-1.6.4-R2.1-forge965-B250

I know many of these, you haven't guaranteed to work with your addons, but I wanted to post three things on here. The first being the most important feature for me. The other two are more bug requests, and I wasn't sure to make individual bug reports for each one. (New-ish to bug reporting still)

The first is: Could you add settings in the config file to disable/enable specific modules, much like the Modular Powersuits config file?

The second when you use the magnet feature, every time you log off, and back into the server - the key binding is lost for it. 

And the last is that occasionally the magnet feature will end up grinding the server to a halt, while the magnet is on. Shutting it off 'resumes' the server, and for the next few seconds mobs begin moving again, at an accelerated rate, and your player rubberbands back to the location the lag originated at.

**Comment by EzerArch** [comment]
> The second when you use the magnet feature, every time you log off, and back into the server - the key binding is lost for it. 

Eximius said it'll be fixed in the next release: http://www.minecraftforum.net/topic/2287651-/page__st__120#entry28685313

**Comment by wiilover22** [comment]
Ah I see. Suppose I should have checked the forums first. Thanks.

**Comment by Eximius88** [comment]
Yes, the keybind issues will be fixed in the next release, I will also try to optimize the magnet as best I can.
