### ISSUE TITLE
i cant craft anything :(

### ISSUE THREAD

**Issue by THEVOLCO** [Eximius88/ModularPowersuitsAddons#14]
i have ic2 and thermal Expansion installed but i cant craf tanything :(

**Comment by THEVOLCO** [comment]
i´m using 1.7.10

**Comment by Eximius88** [comment]
I have tested this in a normal running environment, and have been able to replicate it. I am going to hardcode the recipes in so that you can choose what one you want to use. I have actually been debating completely removing IC2 stuff from MPSA completely, until it is no longer experimental.
