### ISSUE TITLE
Crash while hovering over the components of the wireless terminal module

### ISSUE THREAD

**Issue by lirannl** [Eximius88/ModularPowersuitsAddons#18]
I assume you didn't tweak it to use AE2. And so it tries to show up the original AE1 wireless terminal, which doesn't exist in 1.7.

**Comment by Eximius88** [comment]
I did tweak it for AE2, but didn't actually test to see if it worked. I will work on this right away.

**Comment by lirannl** [comment]
By the way, in RV2, the problem is worse. It crashes at launch (judging by the log, it says things about AE wireless terminals, and your mod, the conclusion is obvious)

**Comment by Eximius88** [comment]
AE2 functionality is severely broken in MPSA. I am trying to fix it, but have been busy with other things lately. Watch the other bug report, and twitter for updates.
