### ISSUE TITLE
Applied Energystics 2 Conflict

### ISSUE THREAD

**Issue by xJon** [Eximius88/ModularPowersuitsAddons#19]
Edit: oops, got the mod name wrong. ugh. not-main-language-english. easier to type "AE2".
All the information ia actually in the AE2 git-hub page.
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/299#issuecomment-59661532
problem with AE2 rv1 stable & MPS addons 901, breaking AE2 wireless terminal. weird.
help?
thanks.

**Comment by mikaldalsbo** [comment]
In Short: 
ModularPowersuitsAddons breaks AE2 Wireless Terminal.

The AE2 Wireless Terminal will not link to player and connect to the AE network after MPS Addons is installed.

**Comment by xJon** [comment]
That is 100% true, and 200% weird. I hope it'll get fixed soon.

**Comment by Keridos** [comment]
Having the same issue, please fix.

**Comment by xJon** [comment]
Anything new?
thanks!

**Comment by Eximius88** [comment]
Yes, I know that I am breaking AE2 functionality. I am trying to fix it, but haven't had much time lately.

**Comment by Agent772** [comment]
Is there an the chance for a fix the next few weeks?

**Comment by TheJulianJES** [comment]
@Eximius88 What API do you using?

**Comment by DrummerMC** [comment]
I have fix the bug and had make a pull request

**Comment by Eximius88** [comment]
Fixed. Thanks DrummerMC and others that helped

**Comment by xJon** [comment]
When the new version with the fix will be out? :)

**Comment by TheJulianJES** [comment]
You can compile it for yourself, download the source, make sure that you installed JDK, then open a command propt in the downloaded and extracted folder, type: gradlew clean setupCIWorkspace build
After that, you wait a bit and you should have a jar in your builds/libs folder. Sorry for bad English, I'm German =)

**Comment by TheJulianJES** [comment]
I can also upload a new version if @Eximius88 allows that.

**Comment by xJon** [comment]
Anything new?

**Comment by Agent772** [comment]
As @TheJulianJES allredy said: 
you could make your own biuld.
Make sure you have JDK (Java Development Kit) installed
1. Download the Repository as .zip File (when on Mainpage of the Repositroy there is a Button on the right side)
2. extract the zip file
   2
3. open cmd (type cmd in the start menu search)
4. drag gradlew.bat into the window.
5. hit SPACE and type "setupDevWorkspace setupDecompWorkspace" without the quotes (case does not matter) and press ENTER/RETURN
6. repeat 3
7. hit SPACE and type "assemble" without the quotes (case does not matter) and press ENTER/RETURN
8. this will make a folder called build. go into it. there is a folder called libs. Go into it. 
   There is your .Jar, and you should know what to do with that.

**Comment by TheJulianJES** [comment]
Okay, I did it diffrent but this should also work, sorry for my English, I'm German..
