### ISSUE TITLE
Unable to disable recipes for ComputerChip, Magnet and solar panel to make custom hard recipe

### ISSUE THREAD

**Issue by Razorskills** [Eximius88/ModularPowersuitsAddons#2]
Exactly what the title says.

I am using this recipe that I have made here:
https://gist.github.com/Razorskills/9682454

But When removing all other recipes, those 3 items still get their default recipe.
I did try changing the recipe inside the jar file to mine. and that didn't seem to work. Is there a easy way to disable the defaults?

**Comment by Eximius88** [comment]
I'm not sure exactly what the problem is, JSON recipes should work with MPSA. I do know that all of my attempts at getting JSON recipes to work with ic2 items have failed. Try changing the ic2 items in your file with vanilla items, "unlocalizedName" : "item.ingotIron"  and see if that works

**Comment by Eximius88** [comment]
Also, where are you putting the recipe file?

**Comment by Eximius88** [comment]
Closed due to no response.
