### ISSUE TITLE
Broken Thermal Expansion required Recipies

### ISSUE THREAD

**Issue by mathwizi2005** [Eximius88/ModularPowersuitsAddons#23]
Using MPS 0.11.0.175 and Numia 0.4.0.99, the recipies that use ANY Thermal Expansion items and components are broken (I have encountered the same issue with MPS itself and already reported it)

Only effects Artificial Muscle and Nitrogen Cooling System, possibly others

**Comment by Eximius88** [comment]
Fixed this along with a few other bugs. Making some more changes before I release an updated build
