### ISSUE TITLE
this is not an issue as such but more of a request

### ISSUE THREAD

**Issue by johnfg2610** [Eximius88/ModularPowersuitsAddons#36]
could you add the abity for mod pack creators to allow enchant ids to be allowed on armor im mainly thinking about soulbound as this gives this armor a disadvantage and i think this would greatly improve the gameplay and working with other mods or at least add a soul bound type armor addon

**Comment by EzerArch** [comment]
Dude, MPSA is now merged with MPS. Eximius hasn't maintained this mod for a loooong time.

**Comment by johnfg2610** [comment]
Really? Ohh lol

**Comment by EzerArch** [comment]
Please don't leave this open.

**Comment by johnfg2610** [comment]
ok
