### ISSUE TITLE
crash on start up

### ISSUE THREAD

**Issue by deadlywolf301** [Eximius88/ModularPowersuitsAddons#37]
Ive tested it and even with just numinia and modular powersuits it crashes and gives me the following error:
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: net.machinemuse.powersuits.common.MPSItems.components()Lnet/machinemuse/powersuits/item/ItemComponent;

**Comment by josephtarbit** [comment]
Same here

**Comment by EzerArch** [comment]
No use to post here. This mod was merged with MPS years ago: https://github.com/MachineMuse/MachineMusePowersuits
