### ISSUE TITLE
Config Directives or how make development environment

### ISSUE THREAD

**Issue by cyberlis** [Eximius88/ModularPowersuitsAddons#4]
I need ability to disable some modules in a config file. If you could make it, it would be great.

I can make it by my self, but i don't know how to make working environment for you project. You can write how to prepare development environment, to work with your project.
I have forge and mcp, but i don't know where to unpack your sources and what additional libraries i need.

Maybe you can upload you development environment with working eclipse (or some else) project.

**Comment by Eximius88** [comment]
You are supposed to be able to disable certain modules, but for some reason that particular issue has been hard to track down. I think I know how to fix it, but it will have to wait until the next release.
