### ISSUE TITLE
r887: module icons are pushed down on screen

### ISSUE THREAD

**Issue by EzerArch** [Eximius88/ModularPowersuitsAddons#7]
Minecraft Version: 1.6.4
Forge Version: 9.11.1.965-MCPatcher
MPS Version: 1.6.4-0.10.0-100
Numina Version:0.1.2-57

All modules icons (clock, feeder, compass etc) were pushed down on the screen.
![2014-05-04_02 57 56](https://cloud.githubusercontent.com/assets/6743303/2872289/3c5828b6-d356-11e3-80aa-1632f754a903.png)

Tested with and without 3rd-party mods.

**Comment by Eximius88** [comment]
Not a bug, but a change made to allow the thaumcraft UI to be visible with the module icons active. Future versions will allow you to move them where ever you want.
